crud_pharm/crud_pharm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('persons/', include('persons.urls')),
    path('products/', include('products.urls')),
    path('pacientes/', include('pacientes.urls')),

]

crud_pharm/pacientes/urls.py
from django.urls import path
from . import views

app_name = "pacientes"

urlpatterns = [
    path("",views.index,name="index"),
    path("section/",views.section,name="section"),
]

crud_pharm/persons/urls.py
from django.urls import path
from . import views
from . import class_views

app_name = "persons"

urlpatterns = [
    path("",views.index,name="index"),
    path("viewPersons/",class_views.PersonsView.as_view(),name="viewPersons"),
    path("addPersons/",class_views.PersonsCreate.as_view(),name="addPersons"),
    path("editPersons/<int:pk>",class_views.PersonsUpdate.as_view(),name="editPersons"),
    path("deletePersons/<int:pk>",class_views.PersonsDelete.as_view(),name="deletePersons"),
]

crud_pharm/products/urls.py
from django.urls import path
from . import views
from . import class_views

app_name = "products"

urlpatterns = [
    path("",views.index,name="index"),
    path("viewProducts/",class_views.ProductsView.as_view(),name="viewProducts"),
    path("addProducts/",class_views.ProductsCreate.as_view(),name="addProducts"),
    path("editProducts/<int:pk>",class_views.ProductsUpdate.as_view(),name="editProducts"),
    path("deleteProducts/<int:pk>",class_views.ProductsDelete.as_view(),name="deleteProducts"),
]

crud_pharm/pacientes/models.py
from django.db import models

# Create your models here.

crud_pharm/persons/models.py
from django.db import models

# Create your models here.


class Persons(models.Model):
    id_person = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)

    def __str__(self):
        """
        Cadena para representar el objeto MyModelName (en el sitio de Admin, etc.)
        """
        return self.first_name

crud_pharm/products/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    id_product = models.AutoField(primary_key=True)
    name_product = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    stock = models.IntegerField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        """
        Cadena para representar el objeto MyModelName (en el sitio de Admin, etc.)
        """
        return self.name_product

crud_pharm/persons/forms.py
from django import forms
from .models import Persons # Importamos el modelo de personsa

class PersonForm(forms.ModelForm):
    class Meta:
        model = Persons
        fields = ('id_person','first_name','last_name','email',)

crud_pharm/products/forms.py
from django import forms
from .models import Products # Importamos el modelo de personsa

class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = '__all__'

crud_pharm/pacientes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def index(request):
    return render(request, "pacientes/index.html")

def section(request):
    
    return render(request, "pacientes/index.html")

crud_pharm/persons/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Persons # Importamos el modelo de personsa
from .forms import PersonForm # Importamos el modelo de personsa

# Create your views here.

def index(request):
    return render(request, "persons/index.html")

def viewPersons(request):
    form=Persons.objects.all()
    ctx={
        'persons_form':form
    }
    return render(request, "persons/viewPersons.html", ctx)

def addPersons(request):
    if request.method == 'GET':
        form=PersonForm()
        ctx={
            'form':form
        }
    else:
        form=PersonForm(request.POST)
        ctx={
            'form':form
        }
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("persons:viewPersons"))
    return render(request, "persons/createPersons.html",ctx)


def editPersons(request, id):
    persons_form=Persons.objects.get(pk = id)
    if request.method == 'GET':
        form=PersonForm(instance = persons_form)
        ctx={
            'form':form
        }
    else:
        form=PersonForm(request.POST, instance = persons_form)
        ctx={
            'form':form
        }
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("persons:viewPersons"))
    return render(request, "persons/createPersons.html",ctx)

def deletePersons(request, id):
    persons_form=Persons.objects.get(pk = id)
    persons_form.delete()
    return HttpResponseRedirect(reverse("persons:viewPersons"))

crud_pharm/products/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Products # Importamos el modelo de personsa

# Create your views here.

def index(request):
    form=Products.objects.all()
    ctx={
        'form':form
    }
    return render(request, "products/index.html", ctx)

crud_pharm/pacientes/templates/pacientes/index.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Pagina de una sola Vista</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q="
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'pacientes/css/style.css' %}" />
  </head>

  <body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
      <div class="item">
        <div class="header">Pacientes</div>
        <div class="menu">
          <a class="item">
            <div>
              <i class="icon tachometer alternate"></i>
              Tablero
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="header">Administración</div>
        <div class="menu">
          <a class="item">
            <div><i class="cogs icon"></i>Configuraciones</div>
          </a>
          <a class="item">
            <div><i class="users icon"></i>Equipo de Desarrollo</div>
          </a>
        </div>
      </div>

      <a
        href="{% url 'pacientes:index' %}"
        class="{% if request.path == '/pacientes/' %} active {% endif %} item"
      >
        <div>
          <i class="icon yellow home line"></i>
          Home
        </div>
      </a>

      <a
        href="{% url 'pacientes:section' %}"
        class="{% if 'section' in request.path %}active{% endif %} item"
      >
        <div>
          <i class="icon green user"></i>
          Pacientes
        </div>
      </a>
      <div class="item">
        <div class="header">Otros</div>
        <div class="menu">
          <a href="#" class="item">
            <div>
              <i class="icon envelope"></i>
              Mensajes
            </div>
          </a>

          <a href="#" class="item">
            <div>
              <i class="icon calendar alternate"></i>
              Calendario de Turnos
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <form action="#">
          <div class="ui mini action input">
            <input type="text" placeholder="Search..." />
            <button class="ui mini icon button">
              <i class="search icon"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="ui segment inverted">
        <div class="ui tiny olive inverted progress">
          <div class="bar" style="width: 54%"></div>
          <div class="label">Monthly Bandwidth</div>
        </div>

        <div class="ui tiny teal inverted progress">
          <div class="bar" style="width: 78%"></div>
          <div class="label">Disk Usage</div>
        </div>
      </div>
    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed inverted menu">
      <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
          <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item"> Clínica de Optometría </a>
      </div>

      <div class="right menu">
        <a href="#" class="item">
          <i class="bell icon"></i>
        </a>
        <div class="ui dropdown item">
          <i class="user cirlce icon"></i>
          <div class="menu">
            <a href="#" class="item">
              <i class="info circle icon"></i> Profile</a
            >
            <a href="#" class="item">
              <i class="wrench icon"></i>
              Settings</a
            >
            <a href="#" class="item">
              <i class="sign-out icon"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>

    <!-- top nav -->
    <!-- Pusher -->
    <div class="pusher">
      <div class="main-content"></div>
    </div>
    <!-- EndPusher -->

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/pacientes/./js/script.js' %}"></script>
  </body>
</html>

crud_pharm/persons/templates/persons/addPersons.html
{% extends "persons/sidebar.html" %} {% load static %}

{% block title %} CreatePersons {% endblock %} {% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="ui two column centered grid">
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
        <div class="column">
          <form class="ui form" method="POST">
            {% csrf_token %}
            <h4 class="ui dividing header">Shipping Information</h4>
            <div class="ui inverted segment">
              <div class="ui inverted form">
                <div class="two fields">
                  <div class="field">
                    <label>First Name</label>
                    {{ form.first_name }}
                  </div>
                  <div class="field">
                    <label>Last Name</label>
                    {{ form.last_name }}
                  </div>
                </div>
                <div class="field">
                  <label>Email</label>
                  {{ form.email }}
                </div>
                <div class="inline field">
                  <div class="ui checkbox">
                    <input type="checkbox" tabindex="0" class="hidden" />
                    <label>I agree to the terms and conditions</label>
                  </div>
                </div>
                <button type="submit" class="ui green submit button">Submit</button>
              </div>
            </div>
          </form>
        </div>
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crud_pharm/persons/templates/persons/persons_list.html
{% extends "persons/sidebar.html" %} {% load static %} {% block title %} View
Persons {% endblock %} {% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="column">
        <table class="ui green celled padded table">
          <thead>
            <tr>
              <th></th>
              <th colspan="5">
                <a href="{% url 'persons:addPersons' %}" class="ui left floated small primary labeled icon button">
                  <i class="user icon"></i> Add User
                </a>
                {% comment %} <div class="ui small button">Approve</div>
                <div class="ui small disabled button">Approve All</div> {% endcomment %}
              </th>
            </tr>
            <th class="single line">#</th>
            <th class="single line">First Name</th>
            <th class="single line">Last Name</th>
            <th>Email</th>
            <th>Actions</th>
          </thead>
          <tbody>
            {% for persons in object_list %}
            <tr>
              <td class="collapsing">{{forloop.counter}}</td>
              <td class="collapsing">{{ persons.first_name }}</td>
              <td class="collapsing">{{ persons.last_name }}</td>
              <td>{{ persons.email }}</td>
              <td class="right aligned collapsing">
                <a
                  href="{% url 'persons:editPersons' persons.id_person %}"
                  class="ui inverted green button"
                  >Edit</a
                >
                <a
                  href="{% url 'persons:deletePersons' persons.id_person %}"
                  class="ui inverted red button"
                  >Delete</a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crud_pharm/persons/templates/persons/sidebar.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}  {% endblock %}</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q="
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
      crossorigin="anonymous"
    />
    
    <link rel="stylesheet" href="{% static 'persons/css/style.css' %}" />
  </head>

  <body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
      <div class="item">
        <div class="header">Persons</div>
        <div class="menu">
          <a class="item">
            <div>
              <i class="icon tachometer alternate"></i>
              Tablero
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="header">
          Administración
        </div>
        <div class="menu">
          <a class="item">
            <div><i class="cogs icon"></i>Configuraciones</div>
          </a>
          <a class="item">
            <div><i class="users icon"></i>Equipo de Desarrollo</div>
          </a>
        </div>
      </div>

      <a href="{% url 'persons:index' %}" class="{% if request.path == '/persons/' %} active {% endif %} item">
        <div>
          <i class="icon yellow home line"></i>
          Home
        </div>
      </a>

      <a href="{% url 'persons:viewPersons' %}" class="{% if 'Persons' in request.path %}active{% endif %} item">
        <div>
          <i class="icon green user"></i>
          Persons
        </div>
      </a>
      <div class="item">
        <div class="header">Otros</div>
        <div class="menu">
          <a href="#" class="item">
            <div>
              <i class="icon envelope"></i>
              Mensajes
            </div>
          </a>

          <a href="#" class="item">
            <div>
              <i class="icon calendar alternate"></i>
              Calendario de Turnos
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <form action="#">
          <div class="ui mini action input">
            <input type="text" placeholder="Search..." />
            <button class="ui mini icon button">
              <i class=" search icon"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="ui segment inverted">
        <div class="ui tiny olive inverted progress">
          <div class="bar" style="width: 54%"></div>
          <div class="label">Monthly Bandwidth</div>
        </div>

        <div class="ui tiny teal inverted progress">
          <div class="bar" style="width:78%"></div>
          <div class="label">Disk Usage</div>
        </div>
      </div>
    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed inverted menu">
      <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
          <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item">
          Clínica de Optometría
        </a>
      </div>

      <div class="right menu">
        <a href="#" class="item">
          <i class="bell icon"></i>
        </a>
        <div class="ui dropdown item">
          <i class="user cirlce icon"></i>
          <div class="menu">
            <a href="#" class="item">
              <i class="info circle icon"></i> Profile</a
            >
            <a href="#" class="item">
              <i class="wrench icon"></i>
              Settings</a
            >
            <a href="#" class="item">
              <i class="sign-out icon"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>
    
    <!-- top nav -->
    <!-- Pusher -->

    {% block body %}

    {% endblock %}

    <!-- EndPusher -->

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/persons/./js/script.js' %}"></script>
  </body>
</html>

crud_pharm/persons/templates/persons/verif.html
{% extends "persons/sidebar.html" %} {% load static %}

{% block title %} CreatePersons {% endblock %} {% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="ui two column centered grid">
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
        <div class="column">
          <form class="ui form" method="POST">
            {% csrf_token %}
            <h4 class="ui dividing header">Delete Information of {{ object }}?</h4>
            <div class="ui inverted segment">
              <div class="ui inverted form">
                <a href="{% url 'persons:viewPersons'%}" class="ui green submit button">Cancel</a> <button type="submit" class="ui red submit button">Delete</button> 
              </div>
            </div>
          </form>
        </div>
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crud_pharm/products/templates/products/addProducts.html
{% extends "products/sidebar.html" %}

{% load static %}

{% block title %} Create Products {% endblock %}

{% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="ui two column centered grid">
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
        <div class="column">
          <form class="ui form" method="POST">
            {% csrf_token %}
            <h4 class="ui dividing header">Shipping Information</h4>
            <div class="ui inverted segment">
              <div class="ui inverted form">
                <div class="field">
                  <label>Products</label>
                  {{ form.name_product }}
                </div>
                <div class="field">
                  <label>Description</label>
                  {{ form.description }}
                </div>
                <div class="field">
                  <label>Stock</label>
                  {{ form.stock }}
                </div>
                <div class="two fields">
                  <div class="field">
                    <label>Created</label>
                    {{ form.created }}
                  </div>
                  <div class="field">
                    <label>Updated</label>
                    {{ form.updated }}
                  </div>
                </div>
                <div class="inline field">
                  <div class="ui checkbox">
                    <input type="checkbox" tabindex="0" class="hidden" />
                    <label>I agree to the terms and conditions</label>
                  </div>
                </div>
                <button type="submit" class="ui green submit button">
                  Submit
                </button>
              </div>
            </div>
          </form>
        </div>
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crud_pharm/products/templates/products/products_list.html
{% extends "products/sidebar.html" %}

{% load static %}

{% block title %} View Products {% endblock %}

{% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="column">
        <table class="ui green celled padded table">
          <thead>
            <tr>
              <th></th>
              <th colspan="6">
                <a href="{% url 'products:addProducts' %}" class="ui left floated small primary labeled icon button">
                  <i class="user icon"></i> Add Products
                </a>
                {% comment %} <div class="ui small button">Approve</div>
                <div class="ui small disabled button">Approve All</div> {% endcomment %}
              </th>
            </tr>
            <th class="single line">#</th>
            <th class="single line">Products</th>
            <th class="single line">Description</th>
            <th>Stock</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Actions</th>
          </thead>
          <tbody>
            {% for products in object_list %}
            <tr>
              <td class="collapsing">{{forloop.counter}}</td>
              <td class="collapsing">{{ products.name_product }}</td>
              <td class="collapsing">{{ products.description }}</td>
              <td>{{ products.stock }}</td>
              <td>{{ products.created }}</td>
              <td>{{ products.updated }}</td>
              <td class="right aligned collapsing">
                <a
                  href="{% url 'products:editProducts' products.id_product %}"
                  class="ui inverted green button"
                  >Edit</a
                >
                <a
                  href="{% url 'products:deleteProducts' products.id_product %}"
                  class="ui inverted red button"
                  >Delete</a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crud_pharm/products/templates/products/sidebar.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}  {% endblock %}</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
      integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q="
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
      crossorigin="anonymous"
    />
    
    <link rel="stylesheet" href="{% static 'products/css/style.css' %}" />
  </head>

  <body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
      <div class="item">
        <div class="header">Products</div>
        <div class="menu">
          <a class="item">
            <div>
              <i class="icon tachometer alternate"></i>
              Tablero
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="header">
          Administración
        </div>
        <div class="menu">
          <a class="item">
            <div><i class="cogs icon"></i>Configuraciones</div>
          </a>
          <a class="item">
            <div><i class="users icon"></i>Equipo de Desarrollo</div>
          </a>
        </div>
      </div>

      <a href="{% url 'products:index' %}" class="{% if request.path == '/products/' %} active {% endif %} item">
        <div>
          <i class="icon yellow home line"></i>
          Home
        </div>
      </a>

      <a href="{% url 'products:viewProducts' %}" class="{% if 'Products' in request.path %}active{% endif %} item">
        <div>
          <i class="icon green user"></i>
          Products
        </div>
      </a>
      <div class="item">
        <div class="header">Otros</div>
        <div class="menu">
          <a href="#" class="item">
            <div>
              <i class="icon envelope"></i>
              Mensajes
            </div>
          </a>

          <a href="#" class="item">
            <div>
              <i class="icon calendar alternate"></i>
              Calendario de Turnos
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <form action="#">
          <div class="ui mini action input">
            <input type="text" placeholder="Search..." />
            <button class="ui mini icon button">
              <i class=" search icon"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="ui segment inverted">
        <div class="ui tiny olive inverted progress">
          <div class="bar" style="width: 54%"></div>
          <div class="label">Monthly Bandwidth</div>
        </div>

        <div class="ui tiny teal inverted progress">
          <div class="bar" style="width:78%"></div>
          <div class="label">Disk Usage</div>
        </div>
      </div>
    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed inverted menu">
      <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
          <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item">
          Clínica de Optometría
        </a>
      </div>

      <div class="right menu">
        <a href="#" class="item">
          <i class="bell icon"></i>
        </a>
        <div class="ui dropdown item">
          <i class="user cirlce icon"></i>
          <div class="menu">
            <a href="#" class="item">
              <i class="info circle icon"></i> Profile</a
            >
            <a href="#" class="item">
              <i class="wrench icon"></i>
              Settings</a
            >
            <a href="#" class="item">
              <i class="sign-out icon"></i>
              Logout
            </a>
          </div>
        </div>
      </div>
    </nav>
    
    <!-- top nav -->
    <!-- Pusher -->

    {% block body %}

    {% endblock %}

    <!-- EndPusher -->

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"
      integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI="
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/products/./js/script.js' %}"></script>
  </body>
</html>

crud_pharm/products/templates/products/verif.html
{% extends "products/sidebar.html" %} {% load static %}

{% block title %} Virificaction of Delete Products {% endblock %} {% block body %}
<div class="pusher">
  <div class="main-content">
    <div class="ui grid stackable padded">
      <div class="ui two column centered grid">
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
        <div class="column">
          <form class="ui form" method="POST">
            {% csrf_token %}
            <h4 class="ui dividing header">Delete Information of {{ object }}?</h4>
            <div class="ui inverted segment">
              <div class="ui inverted form">
                <a href="{% url 'products:viewProducts'%}" class="ui green submit button">Cancel</a> <button type="submit" class="ui red submit button">Delete</button> 
              </div>
            </div>
          </form>
        </div>
        <div class="four column centered row">
          <div class="column"></div>
          <div class="column"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}